apiVersion: v1
kind: Service
metadata:
  name: mca-multicloud-service
spec:
  type: NodePort
  selector:
    app: mca-multicloud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
